<a href="https://colab.research.google.com/github/Mickey87-LG/data_science_krakowiak/blob/main/01_wprowadzenie/01_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python for Data Analysis:
Pandas & NumPy by Coursera


##Import bibliotek

In [1]:
import numpy as np
import pandas as pd
from operator import add, sub



##podstawy NumPy

In [3]:
# Let's define a one-dimensional array
list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
list_1

[50, 60, 80, 100, 200, 300, 500, 600]

In [ ]:
# Let's create a numpy array from the list "my list"

my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [ ]:
type(my_numpy_array)

numpy.ndarray

In [ ]:
my_matrix = np.array([ [3, 7, 9, 3], [4, 3, 2, 2] ])
my_matrix

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

In [ ]:
x = np.random.rand(20)
x

In [ ]:
# randomowa macierz o rozmiarach (x, y)
x = np.random.rand(4, 4)
x

In [ ]:
# randomowa liczba (int) z jakiegos przedzialu
x = np.random.randint(1, 50)
x
# randomowa ilosc liczb z danego przedzialu
x = np.random.randint(0, 100, 5)
x

array([17,  2, 96, 62, 71])

In [ ]:
x = np.arange(1, 50) #bez wartosci y (x, y)
x

In [12]:
s = np.arange(10, 100, 10)
#s = np.arange(start=10, stop=100, step=10)
print(s)

[10 20 30 40 50 60 70 80 90]


In [8]:
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
x = np.ones((6, 6))
x
y = np.zeros((5, 5))
y
print("Macierz jedynek", x)
print("Macierz zer", y)  

In [ ]:
y = np.zeros((4, 10), dtype='int')
#y = np.zeros(shape=(4, 10), dtype='int')
y

In [10]:
#randomowa macierz o rozmiarze 1x10, liczby z zakresu 0 - x (podane przez uzytkownika)
x = int(input('Please enter a positive integer value: '))
x = np.random.randint(0, x, 10)
x

Please enter a positive integer value: 2


array([1, 0, 0, 1, 0, 1, 0, 0, 1, 0])

In [ ]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
z = x + y 
z

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
sqrt = np.sqrt(squared)
sqrt


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x = np.array([5, 7, 20])
y = np.array([9, 15, 4])


In [ ]:
#distance between x and y
z = np.sqrt(x**2 + y**2)
z

array([10.29563014, 16.55294536, 20.39607805])

In [1]:
from operator import add, sub

d = {
    'add': add,
     'sub': sub
}

print(d.get('mul', add)(5, 4))

9


In [6]:
# 1D Array
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


###linspace

In [13]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

###reshape

In [14]:
A = np.arange(15) 
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
A.reshape((3, 5))
#A.reshape((3, -1))  --> 3 wiersze i automatycznie dopiera liczbe kolumn w zaleznosci od wielkosci A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

###podst operacje na tablicach

In [18]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [19]:
A + B

array([6, 0, 7, 4])

In [20]:
A - B

array([0, 2, 1, 0])

In [21]:
A * B

array([ 9, -1, 12,  4])

In [22]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [23]:
A + 3

array([6, 4, 7, 5])

In [24]:
A + 3 * B

array([12, -2, 13,  8])

In [25]:
np.add(A, B)

array([6, 0, 7, 4])

In [26]:
#odejmowanie
np.subtract(A, B)

array([0, 2, 1, 0])

In [27]:
#mnozenie
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [28]:
#dzielenie
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

###mnozenie macierzy (np.dot)

In [31]:
x = np.array([[1, 3], [-2, 0]])
y = np.array([[6, 0], [-1, 2]])
print(x, '\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [30]:
x * y

array([[6, 0],
       [2, 0]])

In [32]:
np.dot(x, y)

array([[  3,   6],
       [-12,   0]])

In [33]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [34]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [35]:
x @ y

array([[  3,   6],
       [-12,   0]])

##Generowanie liczb pseudoloswych (.random)

In [36]:
np.random.seed(0)

In [37]:
np.random.randn()

1.764052345967664

In [38]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [39]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [40]:
np.random.rand()

0.1965823616800535

In [41]:
np.random.randint(10)

0

In [42]:
np.random.randint(10, 101, 5) 

array([79, 10, 60, 46, 44])

In [43]:
np.random.choice([4, 2, 1, 6])

4

In [44]:
np.random.choice(['python', 'java', 'sql'])

'java'

In [45]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.random.shuffle(data)   # zapamietuje zmiane na obiekcie
data

array([2, 1, 3, 5, 4, 8, 6, 9, 0, 7])

##Podstawowe funkcje

###(.exp)

In [2]:
np.exp(1)

2.718281828459045

###(.sqrt)

In [3]:
#zwraca pierwiastek kwadratowy
np.sqrt(9)

3.0

###(.all)(.any)

In [4]:
#sprawdzza czy wszystko to true
np.all([2, 3, 1])

True

In [5]:
np.any([1, 2, 3]) 

True

In [6]:
A = np.random.rand(5)
A 

array([0.58852272, 0.69442454, 0.07092011, 0.13570697, 0.80417838])

###(.argmax)(.argmin)(.argsort)


In [7]:
#zwraca index z najwieksza wartoscia
np.argmax(A)

4

In [8]:
A[np.argmax(A)]

0.8041783780887974

In [9]:
#zwraca idx z najnizsza wartoscia
np.argmin(A)

2

In [13]:
#zwraca posortowane indexy od najmniejszej do najwiekszej
np.argsort(A)

array([2, 3, 0, 1, 4])

###(.max)(.min)(.mean)(.median)(.std)

In [14]:
np.max(A)

0.8041783780887974

In [15]:
np.min(A)

0.07092010732229559

In [16]:
#srednia
np.mean(A)

0.4587505426685851

In [17]:
#mediana
np.median(A)

0.5885227203574542

In [18]:
#odchylenie standardowe
np.std(A) 

0.29882203203112767

##Indeksowanie, Wycinanie

In [19]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [21]:
A[2]

2

In [22]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [23]:
A[:2]

array([0, 1])

In [24]:
A[3:12] # od indexu do indexu

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
A[[0, 2]]  # konkretne indexy

array([0, 2])

In [26]:
A[-1] # zwraca ost element

19

###(.reshape)

In [28]:
A = A.reshape(4, 5)
A 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
#wycinamy konkretny wiersz
A[0]

array([0, 1, 2, 3, 4])

In [31]:
#wycinamy kolumne
A[:, 0] # 0 to index wycinanej kolumny

array([ 0,  5, 10, 15])

In [32]:
A[1, 1]

6

In [34]:
A[1:3, 1:4] 

array([[ 6,  7,  8],
       [11, 12, 13]])

In [36]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

##iteracja po tablicach

In [37]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [38]:
for row in A:
  print(row[0])

0
5
10
15


In [39]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


###(.flat)

In [40]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


##zmiana rozmiaru tablic

In [41]:
A.shape

(4, 5)

In [42]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

###(.ravel)

In [44]:
# wyplaszcza dane
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
# transponowanie tablicy
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

##maski logiczne

In [48]:
A = np.arange(-10, 10, 0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [50]:
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [51]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [52]:
A[A >0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

###(.bitwise_and)

In [54]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [55]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

###(.bitwise_or)

In [56]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])